import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { TooltipProvider } from "@/components/ui/tooltip"
import { Geist, Geist_Mono, Inter } from "next/font/google";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cameron Thrap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body >
        <TooltipProvider>
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
